spring:
  datasource:
    url: jdbc:h2:mem:valorant;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ""
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
      path: /h2
  rsocket:
    server:
      port: 7000
      transport: tcp

logging:
  level:
    org.hibernate.SQL: debug
    org.springframework.rsocket: info 