apiVersion: v1
kind: Namespace
metadata:
  name: app
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: app
type: Opaque
stringData:
  SECRET_KEY: "dev-secret"
  POSTGRES_PASSWORD: "password"
  RABBIT_USER: "guest"
  RABBIT_PASS: "guest"
  MINIO_ACCESS_KEY: "minioadmin"
  MINIO_SECRET_KEY: "minioadmin"
  OPENAI_API_KEY: ""
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: app
data:
  POSTGRES_DB: "postgres"
  POSTGRES_USER: "user"
  AUTH_DATABASE_URL: "postgresql://user:password@postgres:5432/postgres"
  CHAT_DATABASE_URL: "postgresql://user:password@postgres:5432/postgres"
  RABBIT_URL: "amqp://guest:guest@rabbitmq:5672/%2F"
  REQUEST_QUEUE: "ecg_requests"
  RESPONSE_QUEUE: "ecg_responses"
  ECG_BUCKET: "ecg-bucket"
  MINIO_ENDPOINT: "minio:9000"
  NGINX_CONF: |
    worker_processes  1;
    events { worker_connections 1024; }
    http {
      sendfile on;
      upstream auth { server auth-service:8000; }
      upstream chat { server chat-service:8080; }
      upstream ecg  { server ecg-analysis-service:8080; }
      upstream front { server frontend:8000; }

      server {
        listen 80;

        location /api/auth/ { proxy_pass http://auth; }
        location /api/chat/ { proxy_pass http://chat; }
        location /api/ecg/  { proxy_pass http://ecg;  }

        # UI прокси (необязательно, но удобно)
        location /rabbit/   { proxy_pass http://rabbitmq:15672/; }
        location /minio/    { proxy_pass http://minio:9001/; }

        location / { proxy_pass http://front; }
      }
    }
  INIT_SQL: |
    -- создавай нужные роли/БД тут, если надо
    -- пример: CREATE USER auth_user WITH PASSWORD 'password';
    --         CREATE DATABASE auth_db OWNER auth_user;
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: app
data:
  nginx.conf: |-
    {{NGINX_CONF}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
  namespace: app
data:
  init.sql: |-
    {{INIT_SQL}}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: app
spec:
  accessModes: ["ReadWriteOnce"]
  resources: { requests: { storage: 5Gi } }
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
  namespace: app
spec:
  accessModes: ["ReadWriteOnce"]
  resources: { requests: { storage: 10Gi } }
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-pvc
  namespace: app
spec:
  accessModes: ["ReadWriteOnce"]
  resources: { requests: { storage: 2Gi } }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: app
spec:
  replicas: 1
  selector: { matchLabels: { app: postgres } }
  template:
    metadata:
      labels: { app: postgres }
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_DB
              valueFrom: { configMapKeyRef: { name: app-config, key: POSTGRES_DB } }
            - name: POSTGRES_USER
              valueFrom: { configMapKeyRef: { name: app-config, key: POSTGRES_USER } }
            - name: POSTGRES_PASSWORD
              valueFrom: { secretKeyRef: { name: app-secrets, key: POSTGRES_PASSWORD } }
          ports: [{ containerPort: 5432, name: pg }]
          volumeMounts:
            - { name: data, mountPath: /var/lib/postgresql/data }
            - { name: init, mountPath: /docker-entrypoint-initdb.d }
          readinessProbe:
            exec: { command: ["sh","-lc","pg_isready -U $POSTGRES_USER -d $POSTGRES_DB -h 127.0.0.1 -p 5432"] }
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            tcpSocket: { port: 5432 }
            initialDelaySeconds: 20
            periodSeconds: 20
      volumes:
        - name: data
          persistentVolumeClaim: { claimName: postgres-pvc }
        - name: init
          configMap:
            name: postgres-init
            items:
              - key: init.sql
                path: init.sql
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: app
spec:
  selector: { app: postgres }
  ports:
    - name: pg
      port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: app
spec:
  replicas: 1
  selector: { matchLabels: { app: rabbitmq } }
  template:
    metadata:
      labels: { app: rabbitmq }
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management-alpine
          imagePullPolicy: IfNotPresent
          env:
            - name: RABBITMQ_DEFAULT_USER
              valueFrom: { secretKeyRef: { name: app-secrets, key: RABBIT_USER } }
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom: { secretKeyRef: { name: app-secrets, key: RABBIT_PASS } }
          ports:
            - { containerPort: 5672, name: amqp }
            - { containerPort: 15672, name: http }
          volumeMounts:
            - { name: data, mountPath: /var/lib/rabbitmq }
          readinessProbe:
            exec: { command: ["rabbitmq-diagnostics","-q","ping"] }
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            exec: { command: ["rabbitmq-diagnostics","-q","ping"] }
            initialDelaySeconds: 20
            periodSeconds: 20
      volumes:
        - name: data
          persistentVolumeClaim: { claimName: rabbitmq-pvc }
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: app
spec:
  selector: { app: rabbitmq }
  ports:
    - { name: amqp, port: 5672, targetPort: 5672 }
    - { name: http, port: 15672, targetPort: 15672 }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: app
spec:
  replicas: 1
  selector: { matchLabels: { app: minio } }
  template:
    metadata:
      labels: { app: minio }
    spec:
      containers:
        - name: minio
          image: minio/minio:latest
          imagePullPolicy: IfNotPresent
          args: ["server","/data","--console-address",":9001"]
          env:
            - name: MINIO_ROOT_USER
              valueFrom: { secretKeyRef: { name: app-secrets, key: MINIO_ACCESS_KEY } }
            - name: MINIO_ROOT_PASSWORD
              valueFrom: { secretKeyRef: { name: app-secrets, key: MINIO_SECRET_KEY } }
          ports:
            - { containerPort: 9000, name: s3 }
            - { containerPort: 9001, name: console }
          volumeMounts:
            - { name: data, mountPath: /data }
          readinessProbe:
            httpGet: { path: /minio/health/ready, port: 9000 }
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /minio/health/live, port: 9000 }
            initialDelaySeconds: 20
            periodSeconds: 20
      volumes:
        - name: data
          persistentVolumeClaim: { claimName: minio-pvc }
---
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: app
spec:
  selector: { app: minio }
  ports:
    - { name: s3, port: 9000, targetPort: 9000 }
    - { name: console, port: 9001, targetPort: 9001 }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: app
spec:
  replicas: 1
  selector: { matchLabels: { app: auth-service } }
  template:
    metadata:
      labels: { app: auth-service }
    spec:
      containers:
        - name: app
          image: auth_service:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: SECRET_KEY
              valueFrom: { secretKeyRef: { name: app-secrets, key: SECRET_KEY } }
            - name: DATABASE_URL
              valueFrom: { configMapKeyRef: { name: app-config, key: AUTH_DATABASE_URL } }
          ports: [{ containerPort: 8000, name: http }]
          readinessProbe:
            tcpSocket: { port: 8000 }
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            tcpSocket: { port: 8000 }
            initialDelaySeconds: 20
            periodSeconds: 20
      initContainers:
        - name: wait-postgres
          image: busybox
          command: ["sh","-c","until nc -z postgres.app.svc.cluster.local 5432; do sleep 1; done"]
        - name: wait-rabbit
          image: busybox
          command: ["sh","-c","until nc -z rabbitmq.app.svc.cluster.local 5672; do sleep 1; done"]
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: app
spec:
  selector: { app: auth-service }
  ports:
    - { name: http, port: 8000, targetPort: 8000 }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-service
  namespace: app
spec:
  replicas: 1
  selector: { matchLabels: { app: chat-service } }
  template:
    metadata:
      labels: { app: chat-service }
    spec:
      containers:
        - name: app
          image: chat_service:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: DATABASE_URL
              valueFrom: { configMapKeyRef: { name: app-config, key: CHAT_DATABASE_URL } }
            - name: MINIO_ENDPOINT
              valueFrom: { configMapKeyRef: { name: app-config, key: MINIO_ENDPOINT } }
            - name: MINIO_ACCESS_KEY
              valueFrom: { secretKeyRef: { name: app-secrets, key: MINIO_ACCESS_KEY } }
            - name: MINIO_SECRET_KEY
              valueFrom: { secretKeyRef: { name: app-secrets, key: MINIO_SECRET_KEY } }
            - name: ECG_BUCKET
              valueFrom: { configMapKeyRef: { name: app-config, key: ECG_BUCKET } }
            - name: RABBIT_URL
              valueFrom: { configMapKeyRef: { name: app-config, key: RABBIT_URL } }
            - name: REQUEST_QUEUE
              valueFrom: { configMapKeyRef: { name: app-config, key: REQUEST_QUEUE } }
          ports: [{ containerPort: 8080, name: http }]
          readinessProbe:
            tcpSocket: { port: 8080 }
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            tcpSocket: { port: 8080 }
            initialDelaySeconds: 20
            periodSeconds: 20
      initContainers:
        - name: wait-postgres
          image: busybox
          command: ["sh","-c","until nc -z postgres.app.svc.cluster.local 5432; do sleep 1; done"]
        - name: wait-minio
          image: busybox
          command: ["sh","-c","until nc -z minio.app.svc.cluster.local 9000; do sleep 1; done"]
        - name: wait-rabbit
          image: busybox
          command: ["sh","-c","until nc -z rabbitmq.app.svc.cluster.local 5672; do sleep 1; done"]
---
apiVersion: v1
kind: Service
metadata:
  name: chat-service
  namespace: app
spec:
  selector: { app: chat-service }
  ports:
    - { name: http, port: 8080, targetPort: 8080 }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecg-analysis-service
  namespace: app
spec:
  replicas: 1
  selector: { matchLabels: { app: ecg-analysis-service } }
  template:
    metadata:
      labels: { app: ecg-analysis-service }
    spec:
      containers:
        - name: app
          image: ecg_analysis_service:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: RABBIT_URL
              valueFrom: { configMapKeyRef: { name: app-config, key: RABBIT_URL } }
            - name: MINIO_ENDPOINT
              valueFrom: { configMapKeyRef: { name: app-config, key: MINIO_ENDPOINT } }
            - name: MINIO_ACCESS_KEY
              valueFrom: { secretKeyRef: { name: app-secrets, key: MINIO_ACCESS_KEY } }
            - name: MINIO_SECRET_KEY
              valueFrom: { secretKeyRef: { name: app-secrets, key: MINIO_SECRET_KEY } }
            - name: REQUEST_QUEUE
              valueFrom: { configMapKeyRef: { name: app-config, key: REQUEST_QUEUE } }
            - name: RESPONSE_QUEUE
              valueFrom: { configMapKeyRef: { name: app-config, key: RESPONSE_QUEUE } }
            - name: OPENAI_API_KEY
              valueFrom: { secretKeyRef: { name: app-secrets, key: OPENAI_API_KEY } }
          ports: [{ containerPort: 8080, name: http }]
          readinessProbe:
            tcpSocket: { port: 8080 }
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            tcpSocket: { port: 8080 }
            initialDelaySeconds: 20
            periodSeconds: 20
      initContainers:
        - name: wait-minio
          image: busybox
          command: ["sh","-c","until nc -z minio.app.svc.cluster.local 9000; do sleep 1; done"]
        - name: wait-rabbit
          image: busybox
          command: ["sh","-c","until nc -z rabbitmq.app.svc.cluster.local 5672; do sleep 1; done"]
---
apiVersion: v1
kind: Service
metadata:
  name: ecg-analysis-service
  namespace: app
spec:
  selector: { app: ecg-analysis-service }
  ports:
    - { name: http, port: 8080, targetPort: 8080 }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: app
spec:
  replicas: 1
  selector: { matchLabels: { app: frontend } }
  template:
    metadata:
      labels: { app: frontend }
    spec:
      containers:
        - name: app
          image: frontend:latest
          imagePullPolicy: IfNotPresent
          ports: [{ containerPort: 8000, name: http }]
          readinessProbe:
            tcpSocket: { port: 8000 }
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket: { port: 8000 }
            initialDelaySeconds: 15
            periodSeconds: 20
      initContainers:
        - name: wait-rabbit
          image: busybox
          command: ["sh","-c","until nc -z rabbitmq.app.svc.cluster.local 5672; do sleep 1; done"]
        - name: wait-minio
          image: busybox
          command: ["sh","-c","until nc -z minio.app.svc.cluster.local 9000; do sleep 1; done"]
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: app
spec:
  selector: { app: frontend }
  ports:
    - { name: http, port: 8000, targetPort: 8000 }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: app
spec:
  replicas: 1
  selector: { matchLabels: { app: api-gateway } }
  template:
    metadata:
      labels: { app: api-gateway }
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          imagePullPolicy: IfNotPresent
          ports: [{ containerPort: 80, name: http }]
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
          readinessProbe:
            httpGet: { path: /, port: 80 }
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /, port: 80 }
            initialDelaySeconds: 15
            periodSeconds: 20
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-conf
            items:
              - key: nginx.conf
                path: nginx.conf
      initContainers:
        - name: wait-auth
          image: busybox
          command: ["sh","-c","until nc -z auth-service.app.svc.cluster.local 8000; do sleep 1; done"]
        - name: wait-chat
          image: busybox
          command: ["sh","-c","until nc -z chat-service.app.svc.cluster.local 8080; do sleep 1; done"]
        - name: wait-ecg
          image: busybox
          command: ["sh","-c","until nc -z ecg-analysis-service.app.svc.cluster.local 8080; do sleep 1; done"]
        - name: wait-front
          image: busybox
          command: ["sh","-c","until nc -z frontend.app.svc.cluster.local 8000; do sleep 1; done"]
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: app
spec:
  selector: { app: api-gateway }
  ports:
    - { name: http, port: 80, targetPort: 80 }
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  namespace: app
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: local.api
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api-gateway
                port:
                  number: 80
